apiVersion: v1
kind: Service
metadata:
  name: {{ include "ansible-helm-jenkins-demo.fullname" . }}
  labels:
    {{- include "ansible-helm-jenkins-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: "tcp-8080"
  selector:
    {{- include "ansible-helm-jenkins-demo.selectorLabels" . | nindent 4 }}
